### ISSUE TITLE
Not working with Contao 4.13.4

### ISSUE THREAD

**Issue by Anke** [mediamotionag/contao-backend-optim-bundle#1]
Hi, this extension is of great help - thank you for that!

I duplicated a 4.13.1 website and updated the copy to version 4.13.4, but the backend-optim-bundle doesn't seem to be working. There are no ID's, neither for articles nor for pages or modules; not in source code either. No error messages.

Any idea?

Regards,
Anke

**Comment by rorych** [comment]
Hi Anke, thanks yes the logic has changed and we will have to debug the bundle. I hope i will be able to do so within the next week.

**Comment by rorych** [comment]
@Anke I solved the problem in the newest version, can you please update and check if the problem is solved for you too?

**Comment by Anke** [comment]
@rorych I'm afraid it hasn't been solved for me. I updated two different websites to 4.13.5 (including the optim-bundle). No IDs visible anywhere.

**Comment by rorych** [comment]
@Anke Can you test it again. It is important, that you are loged in as an admin. Only backend users that are admins can see the ids.

**Comment by Anke** [comment]
Hi rorych, YES, it's working now. ¡Muchas gracias! (I'm always admin :-))
