### ISSUE TITLE
PHP Wanring on install with clean Contao 5.3 installation

### ISSUE THREAD

**Issue by zweifuchs** [mediamotionag/contao-backend-optim-bundle#6]
After installing contao 5.3 with the composer I try to add the backend optim bundle.

> composer require mediamotionag/contao-backend-optim-bundle

then i get this:

> ./composer.json has been updated
Running composer update mediamotionag/contao-backend-optim-bundle
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
> - Locking mediamotionag/contao-backend-optim-bundle (v3.1.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
> - Downloading mediamotionag/contao-backend-optim-bundle (v3.1.0)
> - Installing mediamotionag/contao-backend-optim-bundle (v3.1.0): Extracting archive
Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.
Generating autoload files
111 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
contao/manager-plugin: Dumping generated plugins file...
contao/manager-plugin: ...done dumping generated plugins file
> @php vendor/bin/contao-setup
Cannot load Xdebug - it was already loaded
PHP Warning:  Class "Memo\BackendOptimBundle\EventListener\DataContainerListener" not found in /var/www/html/vendor/mediamotionag/contao-backend-optim-bundle/src/EventListener/DataContainerListener.php on line 19

Warning: Class "Memo\BackendOptimBundle\EventListener\DataContainerListener" not found in /var/www/html/vendor/mediamotionag/contao-backend-optim-bundle/src/EventListener/DataContainerListener.php on line 19

**Comment by rorych** [comment]
resolved with #7
